//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantCourseSelectionTb
    {
        public int CourseSelectionId { get; set; }
        public int ApplicantId { get; set; }
        public int CourseCode { get; set; }
        public int CourseId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
