//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantsTb
    {
        public int RecordId { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public string RegistrationNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string OtherMobile { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int UserNo { get; set; }
        public string PhotoUrl { get; set; }
        public int CountryId { get; set; }
        public bool IsActive { get; set; }
    }
}
