//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserTestTb
    {
        public int TestRecordId { get; set; }
        public int TestId { get; set; }
        public int CourseId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ApplicantId { get; set; }
        public bool IsCompleted { get; set; }
        public int Questions { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime TestDate { get; set; }
        public int Duration { get; set; }
        public Nullable<System.DateTime> TestStartTime { get; set; }
        public Nullable<int> RightQuestions { get; set; }
        public string Remarks { get; set; }
    }
}
