//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserTestDetailsTb
    {
        public int TestRecordId { get; set; }
        public int TestId { get; set; }
        public int AppUserId { get; set; }
        public int QuestionId { get; set; }
        public string Options { get; set; }
        public bool IsChooseRight { get; set; }
    }
}
