//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserScreenshotTB
    {
        public int ScreenShotId { get; set; }
        public int ApplicantId { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime DateTime { get; set; }
        public string ImageUrl { get; set; }
    }
}
