//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserTb
    {
        public int AppUserRecordId { get; set; }
        public int AppUserId { get; set; }
        public int ApplicantId { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreateOn { get; set; }
        public Nullable<System.DateTime> LoginOn { get; set; }
        public string DeviceId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Token { get; set; }
    }
}
