//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificateInvoiceTb
    {
        public int CertificateInoviceId { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Service { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    }
}
