//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatTb
    {
        public int ChatId { get; set; }
        public int AppUserId { get; set; }
        public int ReceiverId { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Message { get; set; }
        public bool IsSender { get; set; }
        public bool IsRead { get; set; }
    }
}
