//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControllerPermission
    {
        public int CPermissionId { get; set; }
        public Nullable<int> ControllerId { get; set; }
        public Nullable<int> UserNo { get; set; }
        public Nullable<bool> Permission { get; set; }
    }
}
