//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseMaterialTb
    {
        public int CourseMaterialId { get; set; }
        public int CourseId { get; set; }
        public string CourseUrl { get; set; }
        public string MaterialType { get; set; }
        public string FileName { get; set; }
    }
}
