//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataFlowTransferTB
    {
        public int DataFlowTransferredId { get; set; }
        public int ApplicantId { get; set; }
        public Nullable<bool> DataFlowTransferred { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
