//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseTb
    {
        public int ExerciseRecordId { get; set; }
        public string Exercise { get; set; }
        public Nullable<int> StartFrom { get; set; }
        public Nullable<int> EndFrom { get; set; }
    }
}
