//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MdLabScienceDbEntities : DbContext
    {
        public MdLabScienceDbEntities()
            : base("name=MdLabScienceDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppUserScreenshotTB> AppUserScreenshotTBs { get; set; }
        public virtual DbSet<AdditionalDocumentTb> AdditionalDocumentTbs { get; set; }
        public virtual DbSet<ApplicantCourseSelectionTb> ApplicantCourseSelectionTbs { get; set; }
        public virtual DbSet<ApplicantInvoiceTB> ApplicantInvoiceTBs { get; set; }
        public virtual DbSet<ApplicantsTb> ApplicantsTbs { get; set; }
        public virtual DbSet<ApplicantTransactionTB> ApplicantTransactionTBs { get; set; }
        public virtual DbSet<AppUserTb> AppUserTbs { get; set; }
        public virtual DbSet<AppUserTestTb> AppUserTestTbs { get; set; }
        public virtual DbSet<CertificateInvoiceTb> CertificateInvoiceTbs { get; set; }
        public virtual DbSet<CertificationApplicantTB> CertificationApplicantTBs { get; set; }
        public virtual DbSet<ChatTb> ChatTbs { get; set; }
        public virtual DbSet<ControllerPermission> ControllerPermissions { get; set; }
        public virtual DbSet<CountryTb> CountryTbs { get; set; }
        public virtual DbSet<CourseMaterialTb> CourseMaterialTbs { get; set; }
        public virtual DbSet<CourseTb> CourseTbs { get; set; }
        public virtual DbSet<DataFlowTransferTB> DataFlowTransferTBs { get; set; }
        public virtual DbSet<DataFlowVerificationTb> DataFlowVerificationTbs { get; set; }
        public virtual DbSet<ExerciseTb> ExerciseTbs { get; set; }
        public virtual DbSet<QuestionOptionsTb> QuestionOptionsTbs { get; set; }
        public virtual DbSet<QuestionsTB> QuestionsTBs { get; set; }
        public virtual DbSet<TestQuestionOptionTb> TestQuestionOptionTbs { get; set; }
        public virtual DbSet<TestQuestionTb> TestQuestionTbs { get; set; }
        public virtual DbSet<UserController> UserControllers { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<UserMenu> UserMenus { get; set; }
        public virtual DbSet<UserPage> UserPages { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<AppUserTestDetailsTb> AppUserTestDetailsTbs { get; set; }
    }
}
