//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestionOptionTb
    {
        public int TestQuestionOptionId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> JobsId { get; set; }
        public string Options { get; set; }
        public Nullable<bool> IsRightAns { get; set; }
        public int TestId { get; set; }
        public Nullable<int> isSelected { get; set; }
        public string Answer { get; set; }
    }
}
