//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestionTb
    {
        public int TestQuestionRecordId { get; set; }
        public int QuestionId { get; set; }
        public int CourseId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string QuestionContent { get; set; }
        public int TestId { get; set; }
    }
}
