//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPage
    {
        public int PageId { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string icon { get; set; }
        public Nullable<int> MenuId { get; set; }
    }
}
