//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdLabScience.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserController
    {
        public int ControllerId { get; set; }
        public string ControllerName { get; set; }
        public string ControllerUrl { get; set; }
        public Nullable<int> MenuId { get; set; }
    }
}
