name: Deploy to SmarterASP

on:
  push:
    branches:
      - invoice
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Which environment(s) to deploy
        type: choice
        required: true
        default: development
        options:
          - development
          - production
          - both

jobs:
  deploy-development:
    name: Deploy to Development
    if: ${{ (github.event_name == 'push' && github.ref_name == 'invoice') || (github.event_name == 'workflow_dispatch' && (inputs.environment == 'development' || inputs.environment == 'both')) }}
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: development
      api_url: https://development.crashcourseonlin.net
    secrets:
      ftp_server: ${{ secrets.FTP_SERVER }}
      ftp_username: ${{ secrets.FTP_USERNAME }}
      ftp_password: ${{ secrets.FTP_PASSWORD }}
      ftp_server_dir: ${{ secrets.FTP_SERVER_DIR }}

  deploy-production:
    name: Deploy to Production
    if: ${{ (github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'workflow_dispatch' && (inputs.environment == 'production' || inputs.environment == 'both')) }}
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: production
      api_url: https://crashcourseonlin.net
    secrets:
      ftp_server: ${{ secrets.FTP_SERVER_PRODUCTION }}
      ftp_username: ${{ secrets.FTP_USERNAME_PRODUCTION }}
      ftp_password: ${{ secrets.FTP_PASSWORD_PRODUCTION }}
      ftp_server_dir: ${{ secrets.FTP_SERVER_DIR_PRODUCTION }}